### ISSUE TITLE
Support comparing two error stacktraces

### ISSUE THREAD

**Issue by adangel** [pmd/pmd-regression-tester#49]
In order to identify easier, whether a processing error is new or already existed before, we could highlight only the differences within a stacktrace.
So, it would be easier to spot, if only the line numbers changed, but the stacktrace is essentially the same.
Maybe, if only the line numbers have changed, we could skip this processing error for new/removed automatically.

Note: Partially address by #39

**Comment by djydewang** [comment]
> In order to identify easier, whether a processing error is new or already existed before, we could highlight only the differences within a stacktrace.

More specifically, if and only if there is a new error and an old error while processing a file, we‘re able to compare the differences between the two errors. In other cases, e.g. if multiple new and old errors are thrown by the same file, we cannot make the difference comparison, because the error element in the PMD XML report doesn't record which rule threw the error.

**Comment by adangel** [comment]
That's true - currently we don't know from which rule the error stems. Maybe we can think about an improvement in PMD to keep track of this - this however probably requires an updated XML report format...
